/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 健康检查 */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth2/authorization/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 发起 Google 平台登录（Spring Security 自带，302 跳转） */
        get: operations["oauth2AuthorizationGoogle"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/login/oauth2/code/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Google OAuth 回调（Spring Security 自带，处理后 302 回前端） */
        get: operations["oauth2CallbackGoogle"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 退出登录 */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取当前登录用户的资料 */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gmail/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 发起单独的 Gmail 邮箱授权（增量授权读/写邮件权限，302 跳转） */
        get: operations["gmailAuthorize"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workbench": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 工作台数据（KOL 列表 + 侧栏统计） */
        get: operations["getWorkbench"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/kols/{kolId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description KOL ID */
                kolId: components["parameters"]["KolId"];
            };
            cookie?: never;
        };
        /** KOL 详情 + 邮件时间线 */
        get: operations["getKolDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 编辑 KOL（改名 / 校准阶段 / 标记无需回复） */
        patch: operations["updateKol"];
        trace?: never;
    };
    "/api/v1/kols/assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Leader：分配离职遗留（orphaned）达人给指定成员 */
        post: operations["assignKols"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/emails/{emailId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 邮件 ID */
                emailId: components["parameters"]["EmailId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除邮件 */
        delete: operations["deleteEmail"];
        options?: never;
        head?: never;
        /** 标记邮件已读 / 未读 */
        patch: operations["updateEmail"];
        trace?: never;
    };
    "/api/v1/emails/{emailId}/reclassify": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 邮件 ID */
                emailId: components["parameters"]["EmailId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 重新进行 AI 分类 */
        post: operations["reclassifyEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/board": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 看板（KPI + 累计漏斗 + 阶段分布） */
        get: operations["getBoard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/team/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 团队成员列表 + 团队池 */
        get: operations["getTeamMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/team/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 编辑个人资料（角色 / mentor / 飞书运营名） */
        patch: operations["updateTeamProfile"];
        trace?: never;
    };
    "/api/v1/team/depart/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 目标成员 ID */
                userId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Leader：标记成员离职（名下达人转为 orphaned） */
        post: operations["departTeamMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 我的模板列表 */
        get: operations["listTemplates"];
        put?: never;
        /** 新建模板 */
        post: operations["createTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 模板 ID */
                id: components["parameters"]["TemplateId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除模板 */
        delete: operations["deleteTemplate"];
        options?: never;
        head?: never;
        /** 编辑模板 */
        patch: operations["updateTemplate"];
        trace?: never;
    };
    "/api/v1/scheduled-emails": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 定时邮件列表 */
        get: operations["listScheduledEmails"];
        put?: never;
        /** 创建排程 */
        post: operations["createScheduledEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scheduled-emails/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 定时邮件 ID */
                id: components["parameters"]["ScheduledEmailId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 取消定时邮件（仅未发送可取消） */
        delete: operations["cancelScheduledEmail"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync/gmail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 触发 Gmail 同步（增量 / 历史，支持 pageToken） */
        post: operations["triggerGmailSync"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync/gmail/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gmail 同步进度 */
        get: operations["getGmailSyncStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync/feishu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 触发飞书同步（只读拉取 Sheet → kols） */
        post: operations["triggerFeishuSync"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gmail/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 单发邮件（已人工审核后发送） */
        post: operations["sendEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gmail/batch-send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 批量跟进发送 */
        post: operations["batchSendEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/classify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** AI 邮件分类 */
        post: operations["aiClassify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** AI 草稿生成（中英双版） */
        post: operations["aiDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** AI 草稿发送前自检 */
        post: operations["aiCheck"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/translate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 中英互译 */
        post: operations["aiTranslate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description KOL 阶段
         * @enum {string}
         */
        KolStage: "outreach" | "replied" | "negotiating" | "confirmed" | "producing" | "reviewing" | "published" | "paying" | "reinvest" | "declined";
        /**
         * @description KOL 归属状态
         * @enum {string}
         */
        KolStatus: "active" | "unassigned" | "orphaned" | "closed";
        /**
         * @description 主平台
         * @enum {string}
         */
        Platform: "tiktok" | "instagram" | "youtube" | "x" | "other";
        /**
         * @description 邮件方向
         * @enum {string}
         */
        EmailDirection: "inbound" | "outbound";
        /**
         * @description AI 判定的优先级
         * @enum {string}
         */
        AiPriority: "high" | "medium" | "low";
        /**
         * @description KOL 来源
         * @enum {string}
         */
        KolSource: "gmail" | "feishu" | "manual";
        /**
         * @description 工作台视图模式
         * @default mine
         * @enum {string}
         */
        ViewMode: "mine" | "pool" | "all";
        /**
         * @description 团队角色
         * @enum {string}
         */
        UserRole: "leader" | "full_time" | "intern";
        /**
         * @description 用户账号状态
         * @enum {string}
         */
        UserStatus: "pending_approval" | "active" | "departed";
        /** @description 统一错误体 */
        ApiError: {
            /**
             * @description 机器可读的错误码
             * @example BAD_REQUEST
             */
            code: string;
            /**
             * @description 用户可见的中文错误信息
             * @example 请求参数不完整
             */
            message: string;
            /** @description 可选的字段级错误详情 */
            details?: {
                [key: string]: unknown;
            };
        };
        /** @description 分页元信息 */
        PageMeta: {
            /**
             * @description 当前页码（从 1 开始）
             * @example 1
             */
            page: number;
            /**
             * @description 每页条数
             * @example 50
             */
            size: number;
            /**
             * Format: int64
             * @description 总记录数
             * @example 0
             */
            total: number;
        };
        /** @description KOL（达人） */
        Kol: {
            /** Format: uuid */
            id?: string;
            /** @description 联系邮箱 */
            email?: string;
            /** @description 达人名 */
            name?: string | null;
            /** @description 账号 handle */
            handle?: string | null;
            primaryPlatform?: components["schemas"]["Platform"] | null;
            /** @description 频道类型 */
            type?: string | null;
            /** @description 主页链接 */
            externalProfileUrl?: string | null;
            source?: components["schemas"]["KolSource"];
            /** @description 飞书记录 ID */
            feishuRecordId?: string | null;
            /**
             * Format: date-time
             * @description 飞书建联时间
             */
            feishuOutreachAt?: string | null;
            stage?: components["schemas"]["KolStage"];
            status?: components["schemas"]["KolStatus"];
            /**
             * Format: uuid
             * @description 归属成员 ID
             */
            ownerUserId?: string | null;
            /**
             * Format: date-time
             * @description 最近一封来信时间
             */
            lastInboundAt?: string | null;
            /**
             * Format: date-time
             * @description 最近一封去信时间
             */
            lastOutboundAt?: string | null;
            /** @description 约定价格 */
            agreedPrice?: number | null;
            /**
             * Format: date
             * @description 约定截稿日期
             */
            agreedDeadline?: string | null;
            /** @description 备注 */
            notes?: string | null;
            /** @description 手动「无需回复」覆盖标记 */
            replyResolved?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        /** @description KOL 详情（含邮件时间线） */
        KolDetail: {
            kol?: components["schemas"]["Kol"];
            /** @description 归属成员显示名 */
            ownerName?: string | null;
            /** @description 邮件时间线（按时间排序） */
            emails?: components["schemas"]["Email"][];
        };
        /** @description 邮件 */
        Email: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            kolId?: string | null;
            /** Format: uuid */
            userId?: string | null;
            direction?: components["schemas"]["EmailDirection"];
            fromEmail?: string;
            toEmails?: string[];
            ccEmails?: string[] | null;
            subject?: string | null;
            bodyText?: string | null;
            bodyHtml?: string | null;
            /** @description 中文译文 */
            bodyZh?: string | null;
            hasAttachments?: boolean;
            attachmentNames?: string[];
            /** Format: date-time */
            sentAt?: string;
            /** @description AI 推断的阶段信号 */
            aiStageSignal?: components["schemas"]["KolStage"] | null;
            aiPriority?: components["schemas"]["AiPriority"] | null;
            aiSummary?: string | null;
            aiSuggestedAction?: string | null;
            isRead?: boolean;
            /** Format: date-time */
            readAt?: string | null;
            /** Format: date-time */
            createdAt?: string;
        };
        /** @description 邮件模板 */
        EmailTemplate: {
            /** Format: uuid */
            id?: string;
            /** @description 模板名 */
            name?: string;
            /** @description 使用场景 */
            scenario?: string | null;
            /** @description 主题 */
            subject?: string;
            /** @description 正文 */
            body?: string;
            /** @description 使用次数 */
            usedCount?: number;
            /** Format: date-time */
            lastUsedAt?: string | null;
            /** Format: uuid */
            createdBy?: string | null;
            /** Format: date-time */
            createdAt?: string;
        };
        /** @description 定时邮件 */
        ScheduledEmail: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            kolId?: string;
            /** @description 关联达人名（冗余便于展示） */
            kolName?: string | null;
            /** Format: uuid */
            templateId?: string | null;
            toEmail?: string;
            ccEmails?: string[];
            subject?: string;
            englishBody?: string;
            englishBodyHtml?: string | null;
            chineseDraft?: string | null;
            /** Format: date-time */
            scheduledAt?: string;
            /**
             * @description 状态机
             * @enum {string}
             */
            status?: "scheduled" | "processing" | "sent" | "failed";
            attemptCount?: number;
            lastError?: string | null;
            /** Format: date-time */
            createdAt?: string;
        };
        /** @description 用户资料 */
        Profile: {
            /** Format: uuid */
            id?: string;
            displayName?: string;
            email?: string;
            role?: components["schemas"]["UserRole"];
            status?: components["schemas"]["UserStatus"];
            /** Format: uuid */
            mentorUserId?: string | null;
            /** @description 飞书运营名（用于批量归属） */
            feishuOperatorName?: string | null;
            /** @description 是否已完成 Gmail 邮箱授权 */
            gmailAuthorized?: boolean;
            /** Format: date-time */
            lastSyncedAt?: string | null;
            /** Format: date-time */
            createdAt?: string;
        };
        TeamMember: components["schemas"]["Profile"] & {
            /** @description 名下达人数量 */
            ownedKolCount?: number;
        };
        /** @description 团队成员 + 团队池 */
        TeamMembersResponse: {
            members?: components["schemas"]["TeamMember"][];
            /** @description 团队池（待分配 / orphaned 达人） */
            pool?: components["schemas"]["Kol"][];
        };
        WorkbenchKol: components["schemas"]["Kol"] & {
            ownerName?: string | null;
            latestEmail?: components["schemas"]["Email"] | null;
            unreadCount?: number;
            /** @description 需我回复 */
            unreplied?: boolean;
            /** @description 等待对方回复 */
            awaitingReply?: boolean;
        };
        /** @description 工作台侧栏统计 */
        WorkbenchSidebarStats: {
            /** @description 当前视图达人总数 */
            total?: number;
            /** @description 未读数 */
            unread?: number;
            /** @description 需我回复数 */
            unreplied?: number;
            /** @description 各阶段计数 */
            stageCounts?: {
                [key: string]: number;
            };
        };
        /** @description 工作台数据（列表 + 侧栏统计 + 分页） */
        WorkbenchResponse: {
            data?: components["schemas"]["WorkbenchKol"][];
            sidebar?: components["schemas"]["WorkbenchSidebarStats"];
            page?: components["schemas"]["PageMeta"];
        };
        /** @description 看板核心指标 */
        BoardKpi: {
            /** @description 达人总数 */
            totalKols?: number;
            /** @description 进行中达人数 */
            activeKols?: number;
            /** @description 已发布数 */
            publishedKols?: number;
            /** @description 已付款数 */
            paidKols?: number;
            /**
             * Format: float
             * @description 转化率（已付款 / 总数）
             */
            conversionRate?: number;
        };
        /** @description 漏斗单阶段（累计：本阶段及以后人数） */
        BoardFunnelStage: {
            stage?: components["schemas"]["KolStage"];
            /** @description 阶段中文名 */
            label?: string;
            /** @description 累计人数 */
            count?: number;
        };
        /** @description 阶段分布（当前正处于该阶段的人数） */
        BoardStageDistribution: {
            stage?: components["schemas"]["KolStage"];
            label?: string;
            count?: number;
        };
        /** @description 看板汇总（KPI + 累计漏斗 + 阶段分布） */
        BoardSummary: {
            /**
             * @description 当前时间窗
             * @example all
             */
            window?: string;
            kpi?: components["schemas"]["BoardKpi"];
            /** @description 累计漏斗 */
            funnel?: components["schemas"]["BoardFunnelStage"][];
            /** @description 阶段分布 */
            stageDistribution?: components["schemas"]["BoardStageDistribution"][];
        };
        /** @description KOL 编辑请求（按需传字段） */
        KolUpdateRequest: {
            name?: string;
            stage?: components["schemas"]["KolStage"];
            /** @description 标记 / 取消「无需回复」 */
            replyResolved?: boolean;
            notes?: string;
            agreedPrice?: number | null;
            /** Format: date */
            agreedDeadline?: string | null;
        };
        KolAssignRequest: {
            /** @description 待分配的达人 ID 列表 */
            kolIds: string[];
            /**
             * Format: uuid
             * @description 目标归属成员 ID
             */
            ownerUserId: string;
        };
        EmailUpdateRequest: {
            /** @description 标记已读 / 未读 */
            isRead: boolean;
        };
        TeamProfileUpdateRequest: {
            /** @description 工作台显示名 */
            displayName: string;
            role: components["schemas"]["UserRole"];
            /** Format: uuid */
            mentorUserId?: string | null;
            /** @description 飞书运营名（保存后批量归属未分配达人） */
            feishuOperatorName?: string | null;
        };
        TemplateUpsertRequest: {
            name: string;
            scenario?: string | null;
            subject: string;
            body: string;
        };
        ScheduledEmailCreateRequest: {
            /** Format: uuid */
            kolId: string;
            /** Format: uuid */
            templateId?: string | null;
            /** Format: email */
            to: string;
            ccEmails?: string[];
            subject: string;
            englishBody: string;
            englishBodyHtml?: string | null;
            chineseDraft?: string | null;
            /**
             * Format: date-time
             * @description 定时发送时间（必须晚于当前）
             */
            scheduledAt: string;
        };
        GmailSyncRequest: {
            /**
             * @description 同步模式
             * @default incremental
             * @enum {string}
             */
            mode: "incremental" | "history";
            /** @description 历史模式分页游标 */
            pageToken?: string | null;
        };
        /** @description Gmail 同步状态 */
        GmailSyncStatus: {
            running?: boolean;
            /** @enum {string|null} */
            mode?: "incremental" | "history" | null;
            /** @description 已处理邮件数 */
            processed?: number;
            nextPageToken?: string | null;
            /** Format: date-time */
            lastSyncedAt?: string | null;
            lastError?: string | null;
        };
        /** @description 飞书同步状态 */
        FeishuSyncStatus: {
            running?: boolean;
            /** @description upsert 的达人数量 */
            upserted?: number;
            /** Format: date-time */
            lastSyncedAt?: string | null;
            lastError?: string | null;
        };
        SendEmailRequest: {
            /** Format: uuid */
            kolId: string;
            /** Format: email */
            to: string;
            ccEmails?: string[];
            subject: string;
            englishBody: string;
            englishBodyHtml?: string | null;
            chineseDraft?: string | null;
            /** Format: uuid */
            templateId?: string | null;
            /** @description 已人工审核确认（必须为 true） */
            reviewed: boolean;
        };
        SendEmailResult: {
            /** @enum {string} */
            status?: "sent" | "not_configured" | "failed";
            /** @description Gmail 返回的 messageId */
            messageId?: string | null;
            message?: string | null;
        };
        BatchSendRequest: {
            /** @description 批量发送项 */
            items: components["schemas"]["SendEmailRequest"][];
        };
        BatchSendResult: {
            successCount?: number;
            failedCount?: number;
            results?: components["schemas"]["SendEmailResult"][];
        };
        AiClassifyRequest: {
            direction: components["schemas"]["EmailDirection"];
            subject?: string;
            body: string;
            history?: string | null;
        };
        AiClassifyResult: {
            stageSignal?: components["schemas"]["KolStage"] | null;
            priority?: components["schemas"]["AiPriority"] | null;
            summary?: string | null;
            suggestedAction?: string | null;
            extractedFields?: {
                [key: string]: unknown;
            };
            /** @description 是否走了降级 heuristic */
            fallback?: boolean;
        };
        AiDraftRequest: {
            kolName: string;
            /** @default Chloe */
            senderName: string;
            latestEmail: string;
            history?: string;
            templateHint?: string;
            kolStage?: string;
            kolPlatform?: string;
            kolAgreedPrice?: number | null;
        };
        AiDraftResult: {
            /** @description 英文草稿 */
            englishDraft?: string;
            /** @description 中文草稿 */
            chineseDraft?: string;
            fallback?: boolean;
        };
        AiCheckRequest: {
            /** @description 待检查的草稿正文 */
            draft: string;
            subject?: string;
            context?: string | null;
        };
        AiCheckResult: {
            /** @description 发现的问题列表 */
            issues?: {
                /** @enum {string} */
                severity?: "high" | "medium" | "low";
                message?: string;
            }[];
            fallback?: boolean;
        };
        AiTranslateRequest: {
            text: string;
            /**
             * @description 目标语言
             * @default zh
             * @enum {string}
             */
            targetLang: "zh" | "en";
        };
        AiTranslateResult: {
            /** @description 译文 */
            translated?: string;
            /** @enum {string} */
            targetLang?: "zh" | "en";
            fallback?: boolean;
        };
    };
    responses: {
        /** @description 请求参数有误 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description 未登录或会话失效 */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description 无权限 */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description 资源不存在 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
    };
    parameters: {
        /** @description KOL ID */
        KolId: string;
        /** @description 邮件 ID */
        EmailId: string;
        /** @description 模板 ID */
        TemplateId: string;
        /** @description 定时邮件 ID */
        ScheduledEmailId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 服务正常 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description 状态标识
                         * @example UP
                         */
                        status?: string;
                    };
                };
            };
        };
    };
    oauth2AuthorizationGoogle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 重定向到 Google 授权页 */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    oauth2CallbackGoogle: {
        parameters: {
            query?: {
                /** @description Google 返回的授权码 */
                code?: string;
                /** @description 防 CSRF 的 state 值 */
                state?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 登录成功后重定向回前端，并通过 HttpOnly Cookie 写入会话 */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已退出，清除会话 Cookie */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前用户资料 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    gmailAuthorize: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 重定向到 Google Gmail 授权页 */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getWorkbench: {
        parameters: {
            query?: {
                /** @description 视图模式：我的 / 团队池 / 全部 */
                view?: components["schemas"]["ViewMode"];
                /** @description 阶段筛选，阶段枚举或扩展筛选（unread / unreplied）或 all */
                stage?: string;
                /** @description 搜索关键词（达人名 / 邮箱 / 主题） */
                q?: string;
                /** @description 页码，从 1 开始 */
                page?: number;
                /** @description 每页条数 */
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 工作台数据 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkbenchResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getKolDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description KOL ID */
                kolId: components["parameters"]["KolId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description KOL 详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KolDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateKol: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description KOL ID */
                kolId: components["parameters"]["KolId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KolUpdateRequest"];
            };
        };
        responses: {
            /** @description 更新后的 KOL */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Kol"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    assignKols: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KolAssignRequest"];
            };
        };
        responses: {
            /** @description 分配结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description 实际被分配的达人数量 */
                        assignedCount?: number;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    deleteEmail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 邮件 ID */
                emailId: components["parameters"]["EmailId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已删除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateEmail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 邮件 ID */
                emailId: components["parameters"]["EmailId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailUpdateRequest"];
            };
        };
        responses: {
            /** @description 更新后的邮件 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Email"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    reclassifyEmail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 邮件 ID */
                emailId: components["parameters"]["EmailId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 重新分类后的邮件 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Email"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getBoard: {
        parameters: {
            query?: {
                /** @description 时间窗：all / week / month / last30 / 指定月份 yyyy-MM */
                window?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 看板汇总 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardSummary"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getTeamMembers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 团队成员 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamMembersResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateTeamProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamProfileUpdateRequest"];
            };
        };
        responses: {
            /** @description 更新后的资料 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    departTeamMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 目标成员 ID */
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 离职处理结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description 被置为 orphaned 的达人数量 */
                        orphanedCount?: number;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listTemplates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 模板列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["EmailTemplate"][];
                        page?: components["schemas"]["PageMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateUpsertRequest"];
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailTemplate"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    deleteTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 模板 ID */
                id: components["parameters"]["TemplateId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已删除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 模板 ID */
                id: components["parameters"]["TemplateId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateUpsertRequest"];
            };
        };
        responses: {
            /** @description 更新后的模板 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailTemplate"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listScheduledEmails: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 定时邮件列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["ScheduledEmail"][];
                        page?: components["schemas"]["PageMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createScheduledEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduledEmailCreateRequest"];
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduledEmail"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    cancelScheduledEmail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 定时邮件 ID */
                id: components["parameters"]["ScheduledEmailId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已取消 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description 已发送或正在发送，无法取消 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    triggerGmailSync: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["GmailSyncRequest"];
            };
        };
        responses: {
            /** @description 同步任务已受理 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GmailSyncStatus"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getGmailSyncStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 同步进度 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GmailSyncStatus"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    triggerFeishuSync: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 同步任务已受理 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeishuSyncStatus"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    sendEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendEmailRequest"];
            };
        };
        responses: {
            /** @description 发送结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendEmailResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    batchSendEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchSendRequest"];
            };
        };
        responses: {
            /** @description 批量发送结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchSendResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    aiClassify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AiClassifyRequest"];
            };
        };
        responses: {
            /** @description 分类结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        result?: components["schemas"]["AiClassifyResult"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    aiDraft: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AiDraftRequest"];
            };
        };
        responses: {
            /** @description 草稿结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        result?: components["schemas"]["AiDraftResult"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    aiCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AiCheckRequest"];
            };
        };
        responses: {
            /** @description 自检结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        result?: components["schemas"]["AiCheckResult"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    aiTranslate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AiTranslateRequest"];
            };
        };
        responses: {
            /** @description 翻译结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        result?: components["schemas"]["AiTranslateResult"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
}
